name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
    
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  && sudo rm -rf  /usr/bin/chromium  && sudo rm -rf  /usr/bin/chromium-browser

      - name: chrome instances
        uses: browser-actions/setup-chrome@v1
        with:
         chrome-version: 138  # 指定要下载的Chrome[版本] 比如 138、136、128、latest
         install-chromedriver: true

       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        #run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
        run: pip install selenium pyvirtualdisplay && LATEST_CHROME=$(ls -d /opt/hostedtoolcache/setup-chrome/chromium/*/x64/chrome | sort -V | tail -n 1) ; sudo ln -sf "$LATEST_CHROME" /usr/bin/chrome ; ls /opt/hostedtoolcache/setup-chrome/chromium/ > 目前安装的chrome版本目录.txt
        
        
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Running the Python script
        run: |
          curl  'https://vimeo.com/_next/viewer' > 0.html
          sleep 10
          curl -L https://github.com/362227/Python-Selenium-Action/raw/main/gost > gost && sudo chmod 755 ./gost && ./gost -L=:1087 -F=45.32.28.107:1077  &
          sleep 5 && echo 代理ip:&& curl --proxy 127.0.0.1:1087 ifconfig.me
          sudo chmod +x bin/v2ray
          curl -L ${{ secrets.KY_GITHUB_URL }} > bin/ky-github.json && bin/v2ray -config bin/ky-github.json & curl -x 127.0.0.1:1085 -L https://example.com &
          sleep 34
          sudo git clone https://github.com/FlareSolverr/FlareSolverr && cd FlareSolverr && sudo pip install -r requirements.txt && sudo python src/flaresolverr.py &
          python Selenium-Template.py https://vimeo.com/_next/viewer  > vimeo.html
           python Selenium-Template.py https://www.santiago-gonzalez.com/music-videos  > santiago-gonzalez.html
           python Selenium-Template.py https://www.workeditorial.tv/latest-work/  > workeditorial.html
          #抓supjav
          #python Selenium-Template.py https://supjav.com/ja/category/amateur > supjav.html
          #python Selenium-Template.py https://supjav.com/ja/category/amateur/page/2 >> supjav.html


          #删除bin/ky-github.json
          rm -rf bin/ky-github.json
          
      - name: Commit and Push The Results From Python Selenium Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "GitHub Actions Results added"
         git push
